server:
  session-timeout: 1800
spring:
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml

swagger:
  controller: com.songpeng.sparchetype
  description: MES接口管理
  enable: true
  license: wangziyang
  licenseUrl: https://www.cnblogs.com
  title: Api 测试
  version: 1.0.0